const test=require('node:test'),assert=require('node:assert/strict');
const {makeService,defaults}=require('../backend/functions/yiddish-service/core.cjs');
const {claimTeacher}=require('../backend/functions/teacher-claim-core.cjs');
function setup(classId='alpha'){
 const profile={name:'Same Name',passcode:'1234',active:true};
 const config=defaults();config.unlocked=classId==='et'?{et:1,wt:0}:{[classId]:1};config.sections[0].verified=true;
 const data={['b3Games/students/student_unique/profile']:profile,['b3Games/students/student_unique/memberships']:{a:{workspaceId:'b3-2026',classId,active:true}},['b3Games/workspaces/b3-2026/classes/'+classId]:{active:true,members:{student_unique:{name:'Same Name',active:true}},toolGrants:{yiddish:true}},[classId==='et'?'yiddishPrivate/config':'yiddishPrivate/classes/b3-2026/'+classId+'/config']:config,'b3Games/siteSettings':{classAccess:{et:{mode:'open'}}}};
 const store={get:async p=>data[p]??null,set:async(p,v)=>data[p]=v,tx:async(p,f)=>{const v=f(structuredClone(data[p]??null));if(v!==undefined)data[p]=v},update:async changes=>Object.assign(data,changes)};
 return {data,store,service:makeService(store,async token=>token==='owner'?{uid:'owner',email:'simcha5770@gmail.com',email_verified:true}:{uid:'teacher',email:'teacher@test',email_verified:true})};
}
async function login(x,classId='alpha',pin='1234'){return x.service({action:'login',studentId:'student_unique',classId,pin})}
test('Yiddish accepts central individual passcodes and rejects old shared PIN',async()=>{const x=setup();await assert.rejects(login(x,'alpha','5770'),/individual passcode/);assert.ok((await login(x)).token)});
test('blocked student is denied with an existing Yiddish session',async()=>{const x=setup(),{token}=await login(x);x.data['b3Games/students/student_unique/profile'].active=false;await assert.rejects(x.service({action:'status',token}),/turned off/)});
test('changed passcode invalidates a previously issued session',async()=>{const x=setup(),{token}=await login(x);x.data['b3Games/students/student_unique/profile'].passcode='9999';await assert.rejects(x.service({action:'status',token}),/passcode changed/)});
test('class tool revocation blocks Yiddish sessions',async()=>{const x=setup(),{token}=await login(x);x.data['b3Games/workspaces/b3-2026/classes/alpha'].toolGrants.yiddish=false;await assert.rejects(x.service({action:'status',token}),/closed/)});
test('Yiddish rounds support retried answers without advancing twice',async()=>{const x=setup(),{token}=await login(x),{round}=await x.service({action:'start',token,group:0});const body={action:'answer',token,roundId:round.id,index:0,answer:round.question.wordId,requestId:'12345678-1234-1234-1234-123456789012'};const first=await x.service(body),retry=await x.service(body);assert.equal(first.round.index,1);assert.deepEqual(retry,first);assert.ok(x.data['yiddishPrivate/classes/b3-2026/alpha/students/student_unique']);assert.equal(x.data['yiddishPrivate/students/student_unique'],undefined)});
test('B3 retains its legacy progress path with individual passcodes',async()=>{const x=setup('et'),{token}=await login(x,'et');await x.service({action:'start',token,group:0});assert.ok(x.data['yiddishPrivate/students/student_unique'])});
test('teacher cannot load another class Yiddish progress',async()=>{const x=setup();x.data['b3Games/workspaces/b3-2026/teachers/teacher']={active:true,classIds:{beta:true}};await assert.rejects(x.service({action:'teacherLoad',idToken:'teacher',classId:'alpha'}),/not assigned/)});
test('teacher claim preserves class assignments and records UID metadata',async()=>{const x=setup();x.data['b3Games/workspaces/b3-2026/teacherInvites']={inv:{email:'teacher@test',name:'Teacher',active:true,role:'admin',classIds:{alpha:true,'*':true}}};const r=await claimTeacher(x.store,{uid:'new',email:'teacher@test',email_verified:true,firebase:{sign_in_provider:'google.com'}});assert.equal(r.role,'teacher');assert.deepEqual(r.classIds,['alpha']);assert.equal(x.data['b3Games/workspaces/b3-2026/teachers/new'].inviteId,'inv');assert.equal(x.data['b3Games/workspaces/b3-2026/teacherInvites/inv/claimedUid'],'new')});
test('teacher claim rejects unverified or disabled accounts',async()=>{const x=setup();await assert.rejects(claimTeacher(x.store,{uid:'new',email:'teacher@test',email_verified:false}),/verified/);x.data['b3Games/workspaces/b3-2026/teachers/new']={active:false};await assert.rejects(claimTeacher(x.store,{uid:'new',email:'teacher@test',email_verified:true,firebase:{sign_in_provider:'google.com'}}),/disabled/)});

test('Yiddish rejects an explicitly selected class outside the membership',async()=>{const x=setup();await assert.rejects(login(x,'beta'),/Choose an active class/)});
test('Yiddish keeps a previous round usable after a second tab starts another',async()=>{const x=setup(),{token}=await login(x);const first=await x.service({action:'start',token,group:0});await x.service({action:'start',token,group:0});const answer=await x.service({action:'answer',token,roundId:first.round.id,index:0,answer:first.round.question.wordId,requestId:'12345678-1234-1234-1234-123456789012'});assert.equal(answer.round.index,1);assert.equal(answer.round.id,first.round.id)});
test('Yiddish accepts legacy persisted rounds missing result bookkeeping',async()=>{const x=setup('et'),{token}=await login(x,'et'),{round}=await x.service({action:'start',token,group:0});const saved=x.data['yiddishPrivate/students/student_unique'];delete saved.round.results;delete saved.round.responses;const answer=await x.service({action:'answer',token,roundId:round.id,index:0,answer:round.question.wordId,requestId:'12345678-1234-1234-1234-123456789012'});assert.equal(answer.round.index,1)});
