'use strict';
const C=window.YIDDISH_CONTENT,$=id=>document.getElementById(id),API=YiddishAPI;
let group=0,round=null,showAll=false,progress={},config=null,student=null,busy=false,pending=null;
const word=id=>C.words.find(w=>w.id===id),node=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n};
const status=p=>!p?'New':p.credits>=2?'Learned':'Practicing';
function message(s){$('notice').textContent=s}
function block(s){$('lesson').hidden=true;$('practice').hidden=true;document.querySelectorAll('audio').forEach(a=>a.pause());message(s)}
function open(g){return config&&g<config.unlocked[student.classId]&&config.sections[g].verified}
function render(){if(!student||!config)return;if(!round){$('words').hidden=false;$('toolbar').hidden=false;}$('login').hidden=true;$('lesson').hidden=false;$('who').textContent=student.name+' · '+student.classId.toUpperCase();const ids=[...new Set(config.sections.flatMap(s=>s.words))];$('stats').textContent=`${ids.filter(id=>status(progress[id])==='Learned').length} learned · ${ids.filter(id=>status(progress[id])==='Practicing').length} practicing`;$('segments').replaceChildren();config.sections.forEach((s,i)=>{const b=node('button',`${open(i)?'':'🔒 '}Section ${i+1}`,i===group?'active':'');b.disabled=!open(i);b.onclick=()=>{if(busy||pending)return;group=i;showAll=false;round=null;$('practice').hidden=true;render()};$('segments').append(b)});$('words').replaceChildren();$('start').disabled=!open(group);$('readStory').hidden=!open(group);$('readStory').href='story.html?section='+group;$('title').textContent=showAll?'My vocabulary':`Section ${group+1} words`;const visible=showAll?config.sections.flatMap((s,i)=>open(i)?s.words:[]):open(group)?config.sections[group].words:[];for(const id of visible){const w=word(id);if(!w)continue;const card=node('article','','word'),st=status(progress[id]);card.append(node('span',st,'status '+st.toLowerCase()));const yi=node('div',w.yi,'yi');yi.lang='yi';card.append(yi,node('div',w.en));$('words').append(card)}if(!visible.length)$('words').append(node('p','Your teacher will open your next section soon.'));if(round&&open(round.group))question()}
async function refresh(){const s=await API.call('status');student=s.student;config=s.config;progress=s.progress;if(!open(group))group=Math.max(0,config.unlocked[student.classId]-1);if(round&&round.group>=config.unlocked[student.classId])round=null;render()}
async function login(id,pin){const s=await API.call('login',{studentId:id,pin:pin.trim()});sessionStorage.setItem('yiddishSession',s.token);await refresh();message('Progress connected ✓')}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('signIn').disabled=true;try{await login($('name').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),$('pin').value);$('pin').value=''}catch(e){message(e.message)}finally{$('signIn').disabled=false}};
$('all').onclick=()=>{if(busy||pending)return;showAll=!showAll;round=null;$('practice').hidden=true;render()};
$('start').onclick=async()=>{if(busy)return;busy=true;$('start').disabled=true;try{const s=await API.call('start',{group});round=s.round;pending=null;$('practice').hidden=false;question();$('practice').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){message(e.message)}finally{busy=false;$('start').disabled=!open(group)}};
function question(){const box=$('practice');box.hidden=false;box.replaceChildren();$('words').hidden=true;$('toolbar').hidden=true;if(round.finished){box.append(node('h2','Round complete!'),node('p','Your progress is saved. Two first-try correct rounds earn “Learned”.'));const b=node('button','Back to my words');b.onclick=()=>{round=null;box.hidden=true;$('words').hidden=false;$('toolbar').hidden=false;render()};box.append(b);return}const q=round.question,w=word(q.wordId);box.append(node('small',`WORD ${round.index+1} OF ${round.total}`),node('h2','What does this word mean?'));const yi=node('div',w.yi,'yi');yi.lang='yi';box.append(yi);const answers=node('div','');answers.id='answers';const feedback=node('p','');feedback.id='feedback';feedback.setAttribute('role','status');q.choices.forEach(id=>{const b=node('button',word(id).en);b.onclick=()=>submit(id,answers,feedback);answers.append(b)});box.append(answers,feedback);if(pending){answers.querySelectorAll('button').forEach(b=>b.disabled=true);retry(box,answers,feedback)}}
function retry(box,answers,feedback){const b=node('button','Retry saving answer');b.onclick=()=>{b.remove();submit(pending.answer,answers,feedback)};box.append(b)}
async function submit(answer,answers,feedback){if(busy)return;busy=true;answers.querySelectorAll('button').forEach(b=>b.disabled=true);pending=pending||{roundId:round.id,index:round.index,answer,requestId:crypto.randomUUID()};try{const r=await API.call('answer',pending);pending=null;progress=r.progress;if(!r.correct){feedback.textContent='Try another answer.';answers.querySelectorAll('button').forEach(b=>{b.disabled=b.textContent===word(answer).en});return}feedback.textContent=r.firstTry?'Correct!':'You found it. We’ll practice it again.';round=r.round;const next=node('button',round.finished?'See my progress →':'Next word →');next.onclick=()=>{question()};$('practice').append(next)}catch(e){feedback.textContent=e.message;if(e.status===401||e.status===403){block(e.message);$('login').hidden=false}else if(e.status===409){pending=null;round=null;block(e.message);await refresh().catch(()=>{})}else retry($('practice'),answers,feedback)}finally{busy=false}}
(async()=>{try{if(sessionStorage.getItem('yiddishSession')){await refresh();message('Progress connected ✓')}else{const id=localStorage.getItem('b3Games_studentId'),pin=localStorage.getItem('b3Games_classPin');if(id&&pin)await login(id,pin)}}catch(e){block(e.message);$('login').hidden=false}setInterval(async()=>{if(!student||busy||pending)return;try{const s=await API.call('status');config=s.config;student=s.student;if(round&&!open(round.group)){round=null;block('Your teacher closed this section.')}else if(!round){progress=s.progress;render()}}catch(e){block(e.message)}},15000)})();
