const C=YIDDISH_CONTENT,$=id=>document.getElementById(id);let config,roster={},students={},user=null,dirty=false;
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n};
async function call(action,data={}){return YiddishAPI.call(action,{...data,idToken:await user.getIdToken()})}
function notice(t){$('notice').textContent=t}
async function load(){const r=await call('teacherLoad');config=r.config;roster=r.roster;students=r.students;dirty=false;editors();table();notice('Progress loaded.');$('dashboard').hidden=false}
function table(){const t=document.createElement('table'),h=document.createElement('tr');['Student','Track','Learned','Practicing','Last active'].forEach(s=>h.append(node('th',s)));t.append(h);Object.entries(roster).filter(([,v])=>['et','wt'].includes(v.classId)&&($('track').value==='all'||$('track').value===v.classId)).sort((a,b)=>(a[1].name||a[0]).localeCompare(b[1].name||b[0])).forEach(([id,v])=>{const data=students[id]||{},p=data.words||{},learned=C.words.filter(w=>p[w.id]?.credits>=2).length,practicing=C.words.filter(w=>p[w.id]&&p[w.id].credits<2).length,tr=node('tr',''),name=node('button',v.name||id);name.className='student-name';name.onclick=()=>detail(id,v);const td=node('td','');td.append(name);tr.append(td);[v.classId.toUpperCase(),learned,practicing,data.lastActive?new Date(data.lastActive).toLocaleString():'Not started'].forEach(x=>tr.append(node('td',x)));t.append(tr)});$('roster').replaceChildren(t)}
function detail(id,v){const p=students[id]?.words||{};$('detail').replaceChildren(node('h2',v.name||id));const grid=node('div','');grid.className='grid';for(const w of C.words){const card=node('div','');card.className='word';const yi=node('div',w.yi);yi.className='yi';yi.lang='yi';card.append(yi,node('p',w.en),node('span',!p[w.id]?'New':p[w.id].credits>=2?'Learned':'Practicing'));grid.append(card)}$('detail').append(grid)}
function editors(){for(const track of ['et','wt']){$(track).replaceChildren();for(let i=0;i<=4;i++){const o=node('option',i===0?'All closed':String(i));o.value=i;$(track).append(o)}$(track).value=config.unlocked[track]}$('editors').replaceChildren();config.sections.forEach((s,i)=>{const box=node('section','');box.className='section-editor';box.append(node('h3','Section '+(i+1)));for(const [key,title] of [['start','Start second'],['end','End second'],['first','First paragraph'],['last','Last paragraph']]){const label=node('label',title),input=node('input','');input.type='number';input.step=key==='start'||key==='end'?'0.1':'1';input.min='0';input.value=s[key];input.dataset.field=key;label.append(input);box.append(label)}const check=node('label','I checked this audio section and its words'),cb=node('input','');cb.type='checkbox';cb.checked=s.verified;cb.dataset.field='verified';check.prepend(cb);box.append(check);const list=node('div','');list.className='word-checks';C.words.forEach(w=>{const label=node('label',w.yi+' — '+w.en),input=node('input','');input.type='checkbox';input.value=w.id;input.checked=s.words.includes(w.id);input.dataset.word='1';label.prepend(input);list.append(label)});box.append(list);$('editors').append(box)})}
$('save').onclick=async()=>{const draft=structuredClone(config);for(const t of ['et','wt'])draft.unlocked[t]=Number($(t).value);document.querySelectorAll('.section-editor').forEach((box,i)=>{for(const input of box.querySelectorAll('[data-field]'))draft.sections[i][input.dataset.field]=input.type==='checkbox'?input.checked:Number(input.value);draft.sections[i].words=[...box.querySelectorAll('[data-word]:checked')].map(x=>x.value)});$('save').disabled=true;try{const r=await call('teacherSave',{config:draft});config=r.config;dirty=false;notice('Saved. ET and WT will see the updated access.')}catch(e){notice(e.message)}finally{$('save').disabled=false}};
$('dashboard').onchange=()=>dirty=true;$('track').onchange=table;$('reload').onclick=async()=>{if(dirty&&!confirm('Reload and discard unsaved lesson edits?'))return;try{await load()}catch(e){notice(e.message)}};$('signIn').onclick=()=>B3SiteSettings.signInWithGoogle().catch(e=>notice(e.message));$('signOut').onclick=()=>B3SiteSettings.signOut();
C.paras.forEach((p,i)=>{const row=node('p',i+' · '+p);row.dir=i<2?'ltr':'rtl';row.style.fontSize='24px';$('transcript').append(row)});$('audio').src='audio.mp3';
B3SiteSettings.onAuthStateChanged(async(u,ok)=>{user=ok?u:null;$('signIn').hidden=!!user;$('dashboard').hidden=!user;if(user)try{await load()}catch(e){notice(e.message)}else{roster={};students={};$('roster').replaceChildren();$('detail').replaceChildren();notice('Sign in with your teacher Google account.')}});
