const C=YIDDISH_CONTENT,$=id=>document.getElementById(id);let config,roster={},students={},user=null,dirty=false;
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n};
async function call(action,data={}){return YiddishAPI.call(action,{...data,classId:new URLSearchParams(location.search).get('class')||'',idToken:await user.getIdToken()})}
function notice(t){$('notice').textContent=t}
async function load(){const r=await call('teacherLoad');config=r.config;roster=r.roster;students=r.students;dirty=false;editors();table();notice('Progress loaded.');$('dashboard').hidden=false}
function storySummary(data){
  const sd=data.storyDetective||{},g=Number(sd.lastGroup),sec=sd.sections?.[g];
  if(!Number.isInteger(g)||!sec||!sec.answers)return 'Not started';
  const pct=Math.round((Number(sec.firstTryCorrect||0)/Number(sec.answers||1))*100);
  return `S${g+1}: ${Number(sec.lastPosition||0)}/${Number(sec.lastTotal||0)||'?'} · ${pct}% first try`;
}
function table(){const t=document.createElement('table'),h=document.createElement('tr');['Student','Track','Learned','Practicing','Story Detective','Last active'].forEach(s=>h.append(node('th',s)));t.append(h);Object.entries(roster).filter(([,v])=>!!v.classId&&($('track').value==='all'||$('track').value===v.classId)).sort((a,b)=>(a[1].name||a[0]).localeCompare(b[1].name||b[0])).forEach(([id,v])=>{const data=students[id]||{},p=data.words||{},learned=C.words.filter(w=>p[w.id]?.credits>=2).length,practicing=C.words.filter(w=>p[w.id]&&p[w.id].credits<2).length,tr=node('tr',''),name=node('button',v.name||id);name.className='student-name';name.onclick=()=>detail(id,v);const td=node('td','');td.append(name);tr.append(td);[v.classId.toUpperCase(),learned,practicing,storySummary(data),data.lastActive?new Date(data.lastActive).toLocaleString():'Not started'].forEach(x=>tr.append(node('td',x)));t.append(tr)});$('roster').replaceChildren(t)}
function storyDetail(sd){
  const wrap=node('section','');wrap.className='story-teacher-detail';wrap.append(node('h3','Story Detective'));
  for(let g=0;g<4;g++){
    const sec=sd?.sections?.[g]||{},card=node('div','');card.className='story-teacher-card';card.append(node('h4','Section '+(g+1)));
    if(!sec.answers){card.append(node('p','Not started'));wrap.append(card);continue}
    const answers=Number(sec.answers||0),first=Number(sec.firstTryCorrect||0),misses=Number(sec.misses||0),pct=answers?Math.round(first/answers*100):0;
    card.append(node('p',`${answers} paragraph answer${answers===1?'':'s'} · ${pct}% first try · ${misses} miss${misses===1?'':'es'}`));
    card.append(node('p',`Last run position: ${Number(sec.lastPosition||0)}/${Number(sec.lastTotal||0)||'?'} · Completed rounds: ${Number(sec.completedRounds||0)}`));
    const paras=node('div','');paras.className='story-paragraph-stats';
    Object.entries(sec.paragraphs||{}).sort((a,b)=>Number(a[0])-Number(b[0])).forEach(([p,x])=>{const a=Number(x.answers||0),m=Number(x.misses||0),f=Number(x.firstTryCorrect||0);paras.append(node('span',`¶${p}: ${a}×, ${f} first-try, ${m} miss${m===1?'':'es'}`))});
    if(paras.childNodes.length)card.append(paras);wrap.append(card);
  }
  return wrap;
}
function detail(id,v){const data=students[id]||{},p=data.words||{};$('detail').replaceChildren(node('h2',v.name||id),storyDetail(data.storyDetective||{}));const grid=node('div','');grid.className='grid';for(const w of C.words){const card=node('div','');card.className='word';const yi=node('div',w.yi);yi.className='yi';yi.lang='yi';card.append(yi,node('p',w.en),node('span',!p[w.id]?'New':p[w.id].credits>=2?'Learned':'Practicing'));grid.append(card)}$('detail').append(grid)}
const stepsIn=s=>Math.max(1,Math.ceil((s.words||[]).length/4));
function stepRange(i){let a=1;for(let k=0;k<i;k++)a+=stepsIn(config.sections[k]);const b=a+stepsIn(config.sections[i])-1;return a===b?'Step '+a:'Steps '+a+'–'+b}
function stepsOpen(t){const n=config.unlockedSteps&&config.unlockedSteps[t];if(Number.isInteger(n))return n;let s=0;for(let k=0;k<(config.unlocked[t]||0);k++)s+=stepsIn(config.sections[k]);return s}
function sectionsFor(steps){let s=0,k=0;while(k<config.sections.length&&s<steps){s+=stepsIn(config.sections[k]);k++}return k}
function editors(){const ids=Object.keys(config.unlocked||{});const generic=!ids.every(id=>['et','wt'].includes(id));$('wt').closest('label').hidden=generic;$('et').closest('label').firstChild.textContent=generic?'Class steps open ':'ET steps open ';$('wt').closest('label').firstChild.textContent='WT steps open ';$('track').replaceChildren(node('option','All assigned students'),...ids.map(id=>{const o=node('option',id.toUpperCase());o.value=id;return o;}));$('track').firstChild.value='all';for(const track of ['et','wt']){$(track).replaceChildren();const total=config.sections.reduce((n,s)=>n+stepsIn(s),0);for(let i=0;i<=total;i++){const o=node('option',i===0?'All closed':i===1?'Step 1':'Steps 1–'+i);o.value=i;$(track).append(o)}$(track).value=stepsOpen(generic?ids[0]:track)}$('editors').replaceChildren();config.sections.forEach((s,i)=>{const box=node('section','');box.className='section-editor';box.append(node('h3','Section '+(i+1)+' · '+stepRange(i)));for(const [key,title] of [['start','Start second'],['end','End second'],['first','First paragraph'],['last','Last paragraph']]){const label=node('label',title),input=node('input','');input.type='number';input.step=key==='start'||key==='end'?'0.1':'1';input.min='0';input.value=(key==='start'||key==='end')?Math.max(0,Number(s[key])-44):s[key];input.dataset.field=key;label.append(input);box.append(label)}const check=node('label','I checked this audio section and its words'),cb=node('input','');cb.type='checkbox';cb.checked=s.verified;cb.dataset.field='verified';check.prepend(cb);box.append(check);const list=node('div','');list.className='word-checks';C.words.forEach(w=>{const label=node('label',w.yi+' — '+w.en),input=node('input','');input.type='checkbox';input.value=w.id;input.checked=s.words.includes(w.id);input.dataset.word='1';label.prepend(input);list.append(label)});box.append(list);$('editors').append(box)})}
$('save').onclick=async()=>{const draft=structuredClone(config);draft.unlockedSteps=draft.unlockedSteps||{};for(const t of Object.keys(draft.unlocked)){const n=Number($( ['et','wt'].includes(t)?t:'et').value);draft.unlockedSteps[t]=n;draft.unlocked[t]=sectionsFor(n)}document.querySelectorAll('.section-editor').forEach((box,i)=>{for(const input of box.querySelectorAll('[data-field]'))draft.sections[i][input.dataset.field]=input.type==='checkbox'?input.checked:((input.dataset.field==='start'||input.dataset.field==='end')?Number(input.value)+44:Number(input.value));draft.sections[i].words=[...box.querySelectorAll('[data-word]:checked')].map(x=>x.value)});if(draft.sections[0])draft.sections[0].start=0;$('save').disabled=true;try{const r=await call('teacherSave',{config:draft});config=r.config;dirty=false;notice('Saved. Your assigned class will see the updated access.')}catch(e){notice('Not saved: '+e.message);window.scrollTo({top:0,behavior:'smooth'})}finally{$('save').disabled=false}};
$('dashboard').onchange=()=>dirty=true;$('track').onchange=table;$('reload').onclick=async()=>{if(dirty&&!confirm('Reload and discard unsaved lesson edits?'))return;try{await load()}catch(e){notice(e.message)}};$('signIn').onclick=()=>B3SiteSettings.signInWithGoogle().catch(e=>notice(e.message));$('signOut').onclick=()=>B3SiteSettings.signOut();
C.paras.forEach((p,i)=>{if(!p.trim())return;const row=node('p',i+' · '+p);row.dir=i<2?'ltr':'rtl';row.style.fontSize='24px';$('transcript').append(row)});$('audio').src='audio.mp3';
B3SiteSettings.onAuthStateChanged(async(u,ok)=>{user=ok?u:null;$('signIn').hidden=!!user;$('dashboard').hidden=!user;if(user)try{await load()}catch(e){notice(e.message)}else{roster={};students={};$('roster').replaceChildren();$('detail').replaceChildren();notice('Sign in with your teacher Google account.')}});
