(function(){
'use strict';
const C=window.StudentRewardsCommon;
const {db,auth}=C.ensureFirebase();
const ROOT=C.ROOT;
const navItems=['Overview','Daily Points','Students','Rewards','Class Incentives','Reports','Settings','Import Data'];
let state={root:null,tab:'Overview',classId:'',date:C.schoolDateString(),user:null,draftRatings:{},absent:new Set(),importFile:null};
const $=s=>document.querySelector(s);
function path(p=''){return `${ROOT}${p?'/'+p:''}`}
function e(s){return C.escapeHtml(s)}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function categories(){return C.activeCategories(state.root||{})}
function roster(){return C.classRoster(state.root||{},state.classId)}
function activeClasses(){return C.activeClasses(state.root||{})}
function currentClass(){return state.root?.classes?.[state.classId]}
function setTop(t){$('#topTitle').textContent=t}
function toast(m,t){C.toast(m,t)}
function adminOkay(user){return !!(user&&user.email&&user.email.toLowerCase()===C.ADMIN_EMAIL.toLowerCase())}
async function signIn(){try{const p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});await auth.signInWithPopup(p)}catch(err){$('#loginError').textContent=err.message||String(err)}}
async function signOut(){await auth.signOut()}
function buildNav(){const nav=$('#nav');nav.innerHTML=navItems.map(n=>`<button data-tab="${e(n)}">${e(n)}</button>`).join('');nav.onclick=ev=>{const b=ev.target.closest('button[data-tab]');if(!b)return;state.tab=b.dataset.tab;render()}}
async function loadRoot(){const snap=await db.ref(ROOT).once('value');state.root=snap.val()||{};if(!state.classId||!state.root.classes?.[state.classId]?.active)state.classId=activeClasses()[0]?.id||'';prepareDraft();renderClassSelect()}
function subscribe(){db.ref(ROOT).on('value',snap=>{state.root=snap.val()||{};if(!state.classId||!state.root.classes?.[state.classId]?.active)state.classId=activeClasses()[0]?.id||'';renderClassSelect();if(state.tab!=='Daily Points')render()})}
function renderClassSelect(){const el=$('#classSelect');if(!el)return;const rows=activeClasses();el.innerHTML=rows.map(c=>`<option value="${e(c.id)}" ${c.id===state.classId?'selected':''}>${e(c.name)}</option>`).join('');el.onchange=()=>{state.classId=el.value;prepareDraft();render()}}
function prepareDraft(){if(!state.root||!state.classId)return;state.draftRatings={};state.absent=new Set();const cats=categories();for(const s of roster()){
 const att=state.root.dailyAttendance?.[s.id]?.[state.classId]?.[state.date];if(att?.status==='absent')state.absent.add(s.id);
 const saved=state.root.dailyRatings?.[s.id]?.[state.classId]?.[state.date];const source=saved||C.latestRatings(state.root,s.id,state.classId,state.date).ratings||{};
 cats.forEach(cat=>{const found=Object.values(source).find(r=>r.category===cat.name);state.draftRatings[`${s.id}|${cat.name}`]=found?.rating||'Good'})
}}
function render(){if(!state.user||!state.root)return;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));setTop(state.tab);const p=$('#page');
 if(state.tab==='Overview')p.innerHTML=renderOverview();
 if(state.tab==='Daily Points')p.innerHTML=renderDaily();
 if(state.tab==='Students')p.innerHTML=renderStudents();
 if(state.tab==='Rewards')p.innerHTML=renderRewards();
 if(state.tab==='Class Incentives')p.innerHTML=renderClassRewards();
 if(state.tab==='Reports')p.innerHTML=renderReports();
 if(state.tab==='Settings')p.innerHTML=renderSettings();
 if(state.tab==='Import Data')p.innerHTML=renderImport();
 bindPage();
}
function scoreFor(s){return C.cumulativeProgress(C.allProgressRows(state.root,s.id,state.classId))??100}
function renderOverview(){const rs=roster();const avg=rs.length?Math.round(rs.reduce((a,s)=>a+scoreFor(s),0)/rs.length):0;const total=rs.reduce((a,s)=>a+(Number(s.rewardBalance)||0),0);const pending=getRedemptions().filter(x=>x.item.status==='pending').length;return `<div class="pagehead"><div><p class="eyebrow">${e(currentClass()?.name||'CLASS')}</p><h1>Overview</h1><p>Daily effort, point balances and reward requests.</p></div></div><div class="cards"><article class="stat"><span>STUDENTS</span><strong>${rs.length}</strong></article><article class="stat"><span>CLASS PROGRESS</span><strong>${avg}%</strong></article><article class="stat"><span>POINTS IN CIRCULATION</span><strong>${total}</strong></article><article class="stat"><span>PENDING REQUESTS</span><strong>${pending}</strong></article></div><section class="panel"><h2>Student balances</h2><div class="roster">${rs.map(s=>`<article class="student-card"><div class="title"><em class="avatar" style="background:${e(s.color)}">${e(s.initials)}</em><span><h3>${e(s.name)}</h3><p>${scoreFor(s)}% overall progress</p></span></div><div class="balance">${Number(s.rewardBalance)||0} ★</div></article>`).join('')}</div></section>`}
function renderDaily(){const cats=categories(),rs=roster();const saved=rs.some(s=>state.root.dailyAwards?.[s.id]?.[state.classId]?.[state.date]);return `<div class="pagehead"><div><p class="eyebrow">DAILY POINTS</p><h1>${e(currentClass()?.name||'Class')}</h1><p>${saved?'Editing a saved day':'Unsaved day — carried ratings are only a starting point.'}</p></div></div><section class="panel"><div class="toolbar"><label>Date<input id="dailyDate" type="date" value="${e(state.date)}"></label><button id="prevDay" class="ghost">← Previous</button><button id="nextDay" class="ghost">Next →</button><button id="saveDaily" class="primary">${saved?'Update day':'Save day'}</button></div><div class="ratings-table"><div class="ratings-row head" style="--cats:${cats.length}"><div>Student</div><div>Attendance</div>${cats.map(c=>`<div>${e(c.name)}</div>`).join('')}<div>Points</div></div>${rs.map(s=>dailyRow(s,cats)).join('')}</div></section>`}
function dailyRow(s,cats){const absent=state.absent.has(s.id);const ratings=cats.map(c=>state.draftRatings[`${s.id}|${c.name}`]||'Good');const award=C.dailyAward(absent?[]:ratings);return `<div class="ratings-row ${absent?'absentrow':''}" style="--cats:${cats.length}" data-student="${e(s.id)}"><div class="studentcell"><em class="avatar" style="background:${e(s.color)}">${e(s.initials)}</em><b>${e(s.name)}</b></div><div><button class="attendance ${absent?'absent':''}" data-att="${e(s.id)}">${absent?'Absent':'Present'}</button></div>${cats.map(c=>`<div><select class="rating-select" data-rating-student="${e(s.id)}" data-category="${e(c.name)}" ${absent?'disabled':''}>${['Excellent','Good','Fair','Needs Improvement'].map(r=>`<option ${r===(state.draftRatings[`${s.id}|${c.name}`]||'Good')?'selected':''}>${r}</option>`).join('')}</select></div>`).join('')}<div class="points-pill">${award} ★</div></div>`}
async function saveDaily(){
  const updates={}, cats=categories(), rs=roster(), now=new Date().toISOString();
  for(const s of rs){
    const absent=state.absent.has(s.id);
    const ratings={};
    if(!absent){
      for(const cat of cats){
        const rating=state.draftRatings[`${s.id}|${cat.name}`]||'Good';
        ratings[C.categoryKey(cat.name)]={
          category:cat.name,
          rating,
          points:C.progressValue[rating]??100,
          teacherEmail:state.user.email,
          savedAt:now
        };
      }
    }
    const newAward=absent?0:C.dailyAward(cats.map(c=>state.draftRatings[`${s.id}|${c.name}`]||'Good'));
    const oldAward=Number(state.root.dailyAwards?.[s.id]?.[state.classId]?.[state.date]?.points||0);
    const delta=newAward-oldAward;
    const balance=Math.max(0,Number(state.root.students[s.id].rewardBalance||0)+delta);
    updates[`${ROOT}/dailyRatings/${s.id}/${state.classId}/${state.date}`]=absent?null:ratings;
    updates[`${ROOT}/dailyAwards/${s.id}/${state.classId}/${state.date}`]={points:newAward,teacherEmail:state.user.email,savedAt:now};
    updates[`${ROOT}/dailyAttendance/${s.id}/${state.classId}/${state.date}`]={status:absent?'absent':'present',teacherEmail:state.user.email,savedAt:now};
    updates[`${ROOT}/students/${s.id}/rewardBalance`]=balance;
  }
  const auditKey=db.ref(`${ROOT}/audit`).push().key;
  updates[`${ROOT}/audit/${auditKey}`]={actorEmail:state.user.email,action:'daily.saved',details:JSON.stringify({classId:state.classId,date:state.date,count:rs.length}),createdAt:now};
  await db.ref().update(updates);
  toast(`Saved ${rs.length} students for ${state.date}`);
  await loadRoot();
  prepareDraft();
  render();
}
function renderStudents(){const rs=roster();return `<div class="pagehead"><div><p class="eyebrow">STUDENTS</p><h1>${e(currentClass()?.name||'Class')} roster</h1><p>Manage balances and student sign-in.</p></div><button id="addStudentBtn" class="primary">+ Add student</button></div><div class="roster">${rs.map(s=>`<article class="student-card"><div class="title"><em class="avatar" style="background:${e(s.color)}">${e(s.initials)}</em><span><h3>${e(s.name)}</h3><p>Username: ${e(s.username||'not set')}</p></span></div><div class="balance">${Number(s.rewardBalance)||0} ★</div><div class="actions"><button class="secondary" data-addpoints="${e(s.id)}">Add points</button><button class="ghost" data-deduct="${e(s.id)}">Deduct</button><button class="ghost" data-login="${e(s.id)}">Set login</button><button class="danger" data-reset="${e(s.id)}">Reset</button></div></article>`).join('')}</div>`}
async function addStudent(){const name=prompt('Student full name:');if(!name)return;const username=(prompt('Username (optional):')||'').trim().toLowerCase();const pin=username?(prompt('PIN (at least 6 characters):')||''):'';if(username&&pin.length<6)return toast('PIN must be at least 6 characters','error');const id=`student-${uid()}`,initials=name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase(),colors=['#7c3aed','#2563eb','#0891b2','#059669','#d97706','#dc2626','#9333ea','#4f46e5'],color=colors[Math.floor(Math.random()*colors.length)];const updates={};updates[`${ROOT}/students/${id}`]={id,classId:state.classId,name:name.trim(),initials,color,rewardBalance:0,active:true,username};updates[`${ROOT}/enrollments/${state.classId}/${id}`]=true;if(username){const uh=await C.sha256(username);const existing=state.root.privateAuth?.byUsername?.[uh];if(existing)return toast('That username is already in use','error');const ph=await C.sha256(pin);updates[`${ROOT}/privateAuth/byUsername/${uh}`]={studentId:id,username,pinHash:ph}}await db.ref().update(updates);toast('Student added')}
async function setLogin(sid){const s=state.root.students[sid];const username=(prompt('Username:',s.username||'')||'').trim().toLowerCase();if(!username)return;const pin=prompt('New PIN (at least 6 characters):')||'';if(pin.length<6)return toast('PIN must be at least 6 characters','error');const existing=(state.root.privateAuth?.byUsername)||{};const uh=await C.sha256(username);if(existing[uh]&&existing[uh].studentId!==sid)return toast('That username is already in use','error');const updates={};for(const [k,v] of Object.entries(existing)){if(v.studentId===sid&&k!==uh)updates[`${ROOT}/privateAuth/byUsername/${k}`]=null}const ph=await C.sha256(pin);updates[`${ROOT}/students/${sid}/username`]=username;updates[`${ROOT}/privateAuth/byUsername/${uh}`]={studentId:sid,username,pinHash:ph};await db.ref().update(updates);toast('Student login updated')}
async function adjust(sid,mode){const s=state.root.students[sid];let amount;if(mode==='reset'){if(!confirm(`Reset ${s.name}'s balance to 0?`))return;amount=-Number(s.rewardBalance||0)}else{amount=Number(prompt(mode==='add'?'How many points to add?':'How many points to deduct?','5'));if(!Number.isInteger(amount)||amount<=0)return; if(mode==='deduct')amount=-amount}const newBalance=Math.max(0,Number(s.rewardBalance||0)+amount),reason=prompt('Reason:')|| (mode==='reset'?'Reset':'Teacher adjustment'),key=db.ref(`${ROOT}/pointAdjustments`).push().key,now=new Date().toISOString();await db.ref().update({[`${ROOT}/students/${sid}/rewardBalance`]:newBalance,[`${ROOT}/pointAdjustments/${key}`]:{id:key,studentId:sid,classId:state.classId,amount:newBalance-Number(s.rewardBalance||0),action:mode,reason,teacherEmail:state.user.email,createdAt:now}});toast('Balance updated')}
function getRedemptions(){const out=[];for(const [sid,rows] of Object.entries(state.root.redemptionsByStudent||{}))for(const [key,item] of Object.entries(rows||{}))out.push({sid,key,item});return out.sort((a,b)=>String(b.item.requestedAt).localeCompare(String(a.item.requestedAt)))}
function renderRewards(){const rewards=Object.values(state.root.rewards||{}).sort((a,b)=>(a.cost||0)-(b.cost||0)),req=getRedemptions();return `<div class="pagehead"><div><p class="eyebrow">REWARDS</p><h1>Individual privileges</h1><p>These are what students can request with their live point balance.</p></div><button id="addRewardBtn" class="primary">+ Add reward</button></div><div class="rewardgrid">${rewards.map(r=>`<article class="reward-card"><div class="icon" style="background:${e(r.color||'#f3f1ff')}">${e(r.icon||'🎁')}</div><h3>${e(r.name)}</h3><div class="cost">${Number(r.cost)||0} ★</div><p>${r.active?'Active':'Hidden'} · ${r.quantity<0?'Unlimited':`${r.quantity} left`}</p><div class="actions" style="margin-top:12px"><button class="ghost" data-editreward="${e(r.id)}">Edit</button></div></article>`).join('')}</div><section class="panel"><h2>Reward requests</h2><div class="requests">${req.length?req.map(x=>requestRow(x)).join(''):'<p>No reward requests yet.</p>'}</div></section>`}
function requestRow(x){const s=state.root.students?.[x.sid],r=state.root.rewards?.[x.item.rewardId];return `<article class="request"><em class="avatar" style="background:${e(s?.color||'#6849df')}">${e(s?.initials||'?')}</em><span><b>${e(s?.name||x.sid)} — ${e(r?.name||'Reward')}</b><small>${e(x.item.requestedAt||'')} · ${Number(x.item.cost)||0} points</small></span><mark class="badge ${e(x.item.status)}">${e(x.item.status)}</mark>${x.item.status==='pending'?`<button class="secondary" data-approve="${e(x.sid)}|${e(x.key)}">Approve</button><button class="danger" data-decline="${e(x.sid)}|${e(x.key)}">Decline</button>`:''}${x.item.status==='ready'?`<button class="secondary" data-collect="${e(x.sid)}|${e(x.key)}">Collected</button>`:''}</article>`}
async function reviewRedemption(sid,key,decision){const item=state.root.redemptionsByStudent[sid][key],updates={},now=new Date().toISOString();let status=decision==='approve'?'ready':decision==='collect'?'collected':'declined';updates[`${ROOT}/redemptionsByStudent/${sid}/${key}/status`]=status;updates[`${ROOT}/redemptionsByStudent/${sid}/${key}/reviewedBy`]=state.user.email;updates[`${ROOT}/redemptionsByStudent/${sid}/${key}/reviewedAt`]=now;if(decision==='decline')updates[`${ROOT}/students/${sid}/rewardBalance`]=Number(state.root.students[sid].rewardBalance||0)+Number(item.cost||0);await db.ref().update(updates);toast(`Request ${status}`)}
async function editReward(id){const old=id?state.root.rewards[id]:null;const name=prompt('Reward name:',old?.name||'');if(!name)return;const cost=Number(prompt('Point cost:',String(old?.cost??25)));if(!Number.isFinite(cost)||cost<0)return;const icon=prompt('Emoji/icon:',old?.icon||'🎁')||'🎁',active=confirm('Should this reward be active/visible to students?');const rid=id||`reward-${uid()}`;await db.ref(`${ROOT}/rewards/${rid}`).set({id:rid,name:name.trim(),cost:Math.round(cost),icon,color:old?.color||'#ede9fe',active,quantity:old?.quantity??-1});toast(id?'Reward updated':'Reward added')}
function renderClassRewards(){const rows=Object.values(state.root.classRewardCatalog||{}).filter(x=>x.active!==false);return `<div class="pagehead"><div><p class="eyebrow">CLASS INCENTIVES</p><h1>Whole-class rewards</h1><p>These do not spend an individual student's points. Use them when the class earns a group reward.</p></div></div><div class="classrewardgrid">${rows.map(r=>`<article class="classreward-card"><div class="icon">${e(r.icon)}</div><h3>${e(r.name)}</h3><p>Whole-class incentive</p></article>`).join('')}</div><section class="panel"><div class="notice">Current class reward catalog: Charades, Pictionary, Code Game, Copy Cat, BuddyBoardGames, Gimkit, Kahoot, Video, Create a New Game, Extra Game Time, Extra Recess, and Zoom Chat.</div></section>`}
function reportRows(){const out=[];for(const s of roster()){const days=new Set([...Object.keys(state.root.dailyAwards?.[s.id]?.[state.classId]||{}),...Object.keys(state.root.dailyAttendance?.[s.id]?.[state.classId]||{})]);for(const date of [...days].sort().reverse()){const a=state.root.dailyAttendance?.[s.id]?.[state.classId]?.[date],aw=state.root.dailyAwards?.[s.id]?.[state.classId]?.[date];out.push({student:s.name,date,status:a?.status||'present',points:Number(aw?.points||0)})}}return out}
function renderReports(){const rows=reportRows();return `<div class="pagehead"><div><p class="eyebrow">REPORTS</p><h1>Daily point history</h1><p>Export the visible class history to CSV, or print this page to PDF.</p></div><div class="actions"><button id="csvBtn" class="secondary">Export CSV</button><button id="printBtn" class="ghost">Print / PDF</button></div></div><section class="panel report-table"><table><thead><tr><th>Student</th><th>Date</th><th>Attendance</th><th>Points</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.student)}</td><td>${e(r.date)}</td><td>${e(r.status)}</td><td>${r.points}</td></tr>`).join('')}</tbody></table></section>`}
function exportCSV(){const rows=reportRows(),q=v=>`"${String(v).replaceAll('"','""')}"`,csv=[['Student','Date','Attendance','Points'],...rows.map(r=>[r.student,r.date,r.status,r.points])].map(row=>row.map(q).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`student-rewards-${state.classId}-${C.schoolDateString()}.csv`;a.click();URL.revokeObjectURL(a.href)}
function renderSettings(){const enabled=String(state.root.settings?.studentWebsiteEnabled)!=='false';return `<div class="pagehead"><div><p class="eyebrow">SETTINGS</p><h1>Student Rewards settings</h1></div></div><section class="panel"><div class="switchline"><div><h2>Student website access</h2><p>Block or reopen the student portal immediately.</p></div><div id="siteSwitch" class="switch ${enabled?'on':''}"><i></i></div></div></section><section class="panel"><h2>Daily scoring</h2><div class="notice">Excellent = 110% progress, Good = 100%, Fair = 80%, Needs Improvement = 50%. All Good earns 5 daily points; any Excellent with the rest Good/Excellent earns 6.</div></section>`}
function renderImport(){return `<div class="pagehead"><div><p class="eyebrow">ONE-TIME MIGRATION</p><h1>Import old Student Rewards data</h1><p>Use this only for the private migration JSON. Never commit that file to GitHub.</p></div></div><section class="panel"><div class="warning notice">Importing replaces the entire <b>studentRewards</b> Firebase branch. Your old ChatGPT site is not changed.</div><div class="importbox"><input id="importFile" type="file" accept="application/json,.json"><button id="runImport" class="primary" disabled>Import into Firebase</button></div><pre id="importLog" class="importlog">Waiting for a file…</pre></section>`}
async function runImport(){const f=state.importFile;if(!f)return;const log=$('#importLog');try{log.textContent='Reading file…\n';const json=JSON.parse(await f.text());if(!json.meta||!json.students||!json.privateAuth)throw new Error('This is not the Student Rewards migration JSON.');if(!confirm(`Import ${Object.keys(json.students).length} students and replace the current studentRewards branch?`))return;log.textContent+='Writing studentRewards branch…\n';await db.ref(ROOT).set(json);log.textContent+='DONE. Data imported successfully.\n';toast('Migration data imported');}catch(err){log.textContent+=`ERROR: ${err.message||err}\n`;toast('Import failed','error')}}
function bindPage(){
 if(state.tab==='Daily Points'){$('#dailyDate').onchange=ev=>{state.date=ev.target.value;prepareDraft();render()};$('#prevDay').onclick=()=>shiftDate(-1);$('#nextDay').onclick=()=>shiftDate(1);$('#saveDaily').onclick=saveDaily;document.querySelectorAll('[data-att]').forEach(b=>b.onclick=()=>{const id=b.dataset.att;state.absent.has(id)?state.absent.delete(id):state.absent.add(id);render()});document.querySelectorAll('[data-rating-student]').forEach(sel=>sel.onchange=()=>{state.draftRatings[`${sel.dataset.ratingStudent}|${sel.dataset.category}`]=sel.value;render()})}
 if(state.tab==='Students'){$('#addStudentBtn').onclick=addStudent;document.querySelectorAll('[data-addpoints]').forEach(b=>b.onclick=()=>adjust(b.dataset.addpoints,'add'));document.querySelectorAll('[data-deduct]').forEach(b=>b.onclick=()=>adjust(b.dataset.deduct,'deduct'));document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>adjust(b.dataset.reset,'reset'));document.querySelectorAll('[data-login]').forEach(b=>b.onclick=()=>setLogin(b.dataset.login))}
 if(state.tab==='Rewards'){$('#addRewardBtn').onclick=()=>editReward(null);document.querySelectorAll('[data-editreward]').forEach(b=>b.onclick=()=>editReward(b.dataset.editreward));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{const [sid,key]=b.dataset.approve.split('|');reviewRedemption(sid,key,'approve')});document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=()=>{const [sid,key]=b.dataset.decline.split('|');reviewRedemption(sid,key,'decline')});document.querySelectorAll('[data-collect]').forEach(b=>b.onclick=()=>{const [sid,key]=b.dataset.collect.split('|');reviewRedemption(sid,key,'collect')})}
 if(state.tab==='Reports'){$('#csvBtn').onclick=exportCSV;$('#printBtn').onclick=()=>window.print()}
 if(state.tab==='Settings'){$('#siteSwitch').onclick=async()=>{const enabled=String(state.root.settings?.studentWebsiteEnabled)!=='false';await db.ref(`${ROOT}/settings/studentWebsiteEnabled`).set(enabled?'false':'true');toast(enabled?'Student site blocked':'Student site enabled')}}
 if(state.tab==='Import Data'){$('#importFile').onchange=ev=>{state.importFile=ev.target.files?.[0]||null;$('#runImport').disabled=!state.importFile;$('#importLog').textContent=state.importFile?`Ready: ${state.importFile.name}\n`:'Waiting for a file…'};$('#runImport').onclick=runImport}
}
function shiftDate(days){const d=new Date(`${state.date}T12:00:00`);d.setDate(d.getDate()+days);state.date=d.toISOString().slice(0,10);prepareDraft();render()}
$('#googleBtn').onclick=signIn;$('#signOutBtn').onclick=signOut;buildNav();
auth.onAuthStateChanged(async user=>{if(!user){state.user=null;$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');return}if(!adminOkay(user)){await auth.signOut();$('#loginError').textContent=`This page is only authorized for ${C.ADMIN_EMAIL}.`;return}state.user=user;$('#teacherName').textContent=user.displayName||'Rabbi Cohen';$('#teacherEmail').textContent=user.email;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');await loadRoot();subscribe();render()});
})();
